
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
# from tkinter import *
# Explicit imports to satisfy Flake8
import time
from datetime import datetime
from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, messagebox
from Time_Tracker import init_db, login_user, start_tracker, stop_tracker, daily_time_calculator


def loginwindow():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(
        r"C:\Users\mssam\OneDrive\Desktop\COMPUTER NOTES\PYTHON\PROJECTS\Time Tracker\assets\frame0"
    )

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    window = Tk()
    window.geometry("517x517")
    window.configure(bg="#FFFFFF")

    canvas = Canvas(
        window,
        bg="#FFFFFF",
        height=517,
        width=517,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)

    image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
    canvas.create_image(258.0, 258.0, image=image_image_1)

    canvas.create_text(
        217.0, 179.73828125,
        anchor="nw",
        text="Login",
        fill="#FFFFFF",
        font=("Gudea", 32 * -1)
    )

    entry_1 = Entry(
        bd=0,
        bg="#F25C00",
        fg="#FFFFFF",
        insertbackground="white",
        font=("Arial", 12),
        highlightthickness=0
    )
    entry_1.place(x=147, y=252, width=260.0, height=20)

    image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
    canvas.create_image(259.0, 262.0, image=image_image_2)

    def handle_login():
        """Triggered when Login is clicked."""
        user_email = entry_1.get().strip()
        if not user_email:
            messagebox.showwarning("Missing Email", "Please enter your email before logging in.")
            return

        try:
            init_db()
            login_user(user_email)
            messagebox.showinfo("Login Successful", f"Welcome, {user_email}!")
            window.destroy()
            start_page()  # open next GUI
        except Exception as e:
            messagebox.showerror("Error", f"An error occurred: {e}")

    button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=handle_login,
        relief="flat"
    )
    button_1.place(x=108.0, y=303.0, width=301.0, height=30.0)

    canvas.create_text(
        183.0, 432.0,
        anchor="nw",
        text="Time and tide wait for no man",
        fill="#FFFFFF",
        font=("Martel Regular", 10 * -1)
    )

    window.resizable(False, False)
    window.mainloop()

def start_page():
        
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\mssam\OneDrive\Desktop\COMPUTER NOTES\PYTHON\PROJECTS\Time Tracker\assets_1\frame0")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Tk()

    window.geometry("517x517")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 517,
        width = 517,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        258.205078125,
        258.064453125,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        258.0,
        185.0,
        image=image_image_2
    )
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    def open_calculator():
        window.destroy()  # close start_page window
        calculator()      # open calculator window

    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=open_calculator,
        relief="flat"
    )
    button_1.place(
        x=462.0,
        y=23.0,
        width=35.0,
        height=39.0
    )
    # Timer text
    timer_text = canvas.create_text(
        168.0,
        146.0,
        anchor="nw",
        text="00:00:00",
        fill="#FFFFFF",
        font=("Inter", 48 * -1)
    )

    timer_running = False
    start_time = None
    current_phrase = None

    def update_timer():
        nonlocal timer_running, start_time, timer_text
        if timer_running and start_time:
            elapsed = datetime.now() - start_time
            total_seconds = int(elapsed.total_seconds())
            minutes, seconds = divmod(total_seconds, 60)
            hours, minutes = divmod(minutes, 60)
            display_time = f"{hours:02d}:{minutes:02d}:{seconds:02d}"
            canvas.itemconfig(timer_text, text=display_time)
            window.after(1000, update_timer)

    def handle_start():
        nonlocal current_phrase, timer_running, start_time
        phrase = start_tracker()
        if phrase:
            current_phrase = phrase
            start_time = datetime.now()
            timer_running = True
            update_timer()
            messagebox.showinfo("Tracker Started", f"Tracking started!\nSession ID:\n{phrase}")

    def handle_stop():
        nonlocal current_phrase, timer_running, start_time, timer_text
        if not timer_running:
            messagebox.showwarning("Tracker", "No active tracker to stop.")
            return
        if not current_phrase:
            messagebox.showwarning("Tracker", "No active session found to stop.")
            return

        timer_running = False
        success = stop_tracker(current_phrase)
        if success:
            end_time = datetime.now()
            total = end_time - start_time
            total_seconds = int(total.total_seconds())
            minutes, seconds = divmod(total_seconds, 60)
            hours, minutes = divmod(minutes, 60)
            final_display = f"{hours:02d}:{minutes:02d}:{seconds:02d}"
            # ✅ update the canvas timer text
            canvas.itemconfig(timer_text, text=final_display)
            messagebox.showinfo("Tracker", f"Tracking stopped!\nTotal time worked: {final_display}")
            current_phrase = None

            
            
    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=handle_start,
        activebackground="#AFAFAF",
        relief="flat"
    )
    button_2.place(
        x=59.0,
        y=308.0,
        width=166.0,
        height=50.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=handle_stop,
        activebackground="#AFAFAF",
        relief="flat"
    )
    button_3.place(
        x=292.0,
        y=308.0,
        width=169.0,
        height=50.0
    )
    window.resizable(False, False)
    window.mainloop()
    

def calculator():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(
        r"C:\Users\mssam\OneDrive\Desktop\COMPUTER NOTES\PYTHON\PROJECTS\Time Tracker\assets_2\frame0"
    )

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    window = Tk()
    window.geometry("517x517")
    window.configure(bg="#FFFFFF")

    canvas = Canvas(window, bg="#FFFFFF", height=517, width=517, bd=0, highlightthickness=0, relief="ridge")
    canvas.place(x=0, y=0)

    # Background images
    image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
    canvas.create_image(258.0, 328.0, image=image_image_1)
    image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
    canvas.create_image(258.0, 277.0, image=image_image_2)
    image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        147.0,
        262.0,
        image=image_image_3
    )

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        371.0,
        262.0,
        image=image_image_4
    )

    # Text labels
    canvas.create_text(86.0, 130.0, anchor="nw", text="FROM", fill="#000000", font=("IstokWeb Regular", 24 * -1))
    canvas.create_text(370.0, 130.0, anchor="nw", text="TO", fill="#000000", font=("IstokWeb Regular", 24 * -1))
    canvas.create_text(61.0, 186.0, anchor="nw", text="YYYY-MM-DD", fill="#000000", font=("IstokWeb Regular", 24 * -1))
    canvas.create_text(312.0, 186.0, anchor="nw", text="YYYY-MM-DD", fill="#000000", font=("IstokWeb Regular", 24 * -1))

    # Timer display
    timer_text_id = canvas.create_text(181.0, 316.0, anchor="nw", text="00:00:00", fill="#000000", font=("IstokWeb Regular", 40 * -1))

    # Entry fields
    entry_1 = Entry(bd=0, bg="#AFAFAF", fg="#000716", highlightthickness=0)  # TO date
    entry_1.place(x=259.0, y=240.0, width=224.0, height=39.0)
    entry_2 = Entry(bd=0, bg="#858585", fg="#000716", highlightthickness=0)  # FROM date
    entry_2.place(x=33.0, y=240.0, width=215.0, height=39.0)

    # Button 2: Calculate total time for the given date range
    def calculate_total_time():
        from_date = entry_2.get().strip()
        to_date = entry_1.get().strip()
        if not from_date or not to_date:
            messagebox.showwarning("Missing Dates", "Please enter both FROM and TO dates.")
            return
        try:
            # Call your updated daily_time_calculator that supports from_date and to_date
            total_time = daily_time_calculator(from_date=from_date, to_date=to_date)
        except Exception as e:
            messagebox.showerror("Error", f"Invalid date format or error:\n{e}")
            return

        # Display in HH:MM:SS format
        total_seconds = int(total_time.total_seconds())
        hours, remainder = divmod(total_seconds, 3600)
        minutes, seconds = divmod(remainder, 60)
        display_text = f"{hours:02d}:{minutes:02d}:{seconds:02d}"
        canvas.itemconfig(timer_text_id, text=display_text)

    # Button 1: Go back to start timer
    def back_to_start():
        window.destroy()  # Close calculator window
        start_page()      # Open start timer window

    # Buttons
    button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
    button_1 = Button(image=button_image_1, borderwidth=0, highlightthickness=0, command=back_to_start, relief="flat")
    button_1.place(x=454.0, y=30.0, width=35.0, height=35.0)

    button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
    button_2 = Button(image=button_image_2, borderwidth=0, highlightthickness=0, command=calculate_total_time, relief="flat")
    button_2.place(x=147.0, y=384.0, width=224.0, height=34.0)

    window.resizable(False, False)
    window.mainloop()

if __name__ == "__main__":
    loginwindow()
    
